name: Generate benchmarks
on: workflow_dispatch
jobs:
  benchmark:
    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update && sudo apt-get install -y nasm ffmpeg
      - id: cache-video
        uses: actions/cache@v4
        with:
          path: video.264
          key: video
      - if: steps.cache-video.outputs.cache-hit != 'true'
        run: wget -q -O - "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4" | ffmpeg -i - -vcodec copy -bsf h264_mp4toannexb -an video.264
      - run: make
      - run: git clone --depth=1 https://github.com/cisco/openh264.git && make -C openh264
      - run: pip3 install matplotlib --quiet
      - run: PATH="${PWD}:${PWD}/openh264:$PATH" python3 ./misc-scripts/benchmark.py video.264 1 ${GITHUB_STEP_SUMMARY}
