name: Benchmarks
on: workflow_dispatch
jobs:
  benchmarks:
    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    outputs:
      results_x64: ${{ steps.results.outputs.results_x64 }}
      results_arm64: ${{ steps.results.outputs.results_arm64 }}
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update && sudo apt-get install -y nasm ffmpeg clang cmake
      - id: cache-video
        uses: actions/cache@v4
        with:
          path: video.264
          key: video
      - if: steps.cache-video.outputs.cache-hit != 'true'
        run: wget -q -O - "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4" | ffmpeg -i - -vcodec copy -bsf h264_mp4toannexb -an video.264
      - run: |
          make STATIC=yes
          mv edge264_test edge264_test-gcc
      - run: |
          make clear
          make STATIC=yes CC=clang
          mv edge264_test edge264_test-clang
      - run: |
          git clone --depth=1 https://github.com/cisco/openh264.git
          make -C openh264
      - run: |
          git clone --depth=1 https://github.com/ittiam-systems/libavc.git
          mkdir libavc/build
          cd libavc/build
          cmake ..
          make
          cd ../..
      - id: results
        run: |
          results=$(PATH="${PWD}:${PWD}/openh264:${PWD}/libavc/build:${PATH}" python3 ./misc-scripts/bench-decoders.py video.264 5)
          echo "${results}"
          echo "results_${{ matrix.arch }}=${results}" >> "$GITHUB_OUTPUT"
  charts:
    needs: benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RESULTS_X64: ${{ needs.benchmarks.outputs.results_x64 }}
      RESULTS_ARM64: ${{ needs.benchmarks.outputs.results_arm64 }}
    steps:
      - uses: actions/checkout@v5
      - run: |
          pip3 install matplotlib --quiet
          results="{\"x86-64\":${RESULTS_X64},\"arm64\":${RESULTS_ARM64}}"
          echo "${results}"
          python3 ./misc-scripts/bench-charts.py "${results}" README-benchmark.svg
      - uses: actions/upload-artifact@v4
        with:
          path: README-benchmark.svg
      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f README-benchmark.svg
          git commit -m "[Benchmarks] Update figure"
          git push
